### ISSUE TITLE
Mod 2 - Slides 8 & 9 - duplicate content

### ISSUE THREAD

**Issue by midspear** [redhat-gpe/bxms_advanced_infrastructure#23]
**Problem:** In module 2, slides 8 & 9 appear to cover the same content. As an interim fix, my team removed m02s08_bypass_auth_user.adoc was removed from the AllSlides file. 

**Solution:** Please either add correct content to slide 8 or remove it from the deck.

**Comment by jbride** [comment]
Appears to have been fixed with commit:  7075b33dbc7f3c2a5e53e4399cc0d174eaf8d677
