### ISSUE TITLE
Mod 3 - Slides not included in AllSlides

### ISSUE THREAD

**Issue by midspear** [redhat-gpe/bxms_advanced_infrastructure#24]
In module 3, the slides listed below are not included in the AllSlides file. If they are supposed to be part of the module, please add them to the AllSlides.txt file. If they're not supposed to be part of the module, consider moving them to another folder to avoid confusion in the future.

* based_on_kieserver.adoc
* dserver_parameters05.adoc
* runtime_only.adoc

**Comment by jbride** [comment]
done
