### ISSUE TITLE
[All Modules] - Slides display asciidoc errors on RHSE

### ISSUE THREAD

**Issue by honghuac** [redhat-gpe/bxms_advanced_infrastructure#28]
All slides in the modules contain asciidoc errors like these (e.g. :scrollbar :data-uri):

<img width="942" alt="bxms" src="https://cloud.githubusercontent.com/assets/8625482/22203830/d808b2d0-e1a9-11e6-91d0-ea76babb4c45.png">
<img width="948" alt="bxms2" src="https://cloud.githubusercontent.com/assets/8625482/22203831/d80c2460-e1a9-11e6-8354-f9ea3ddd042d.png">

**Comment by midspear** [comment]
@btison  & @honghuac  - My team fixed this issue during the tech writer review. The files just need to be tagged and uploaded to Dokeos whenever you're done resolving other open issues.

**Comment by jbride** [comment]
Slides built iin Jenkins do include this fix.
I'll close this issue and tag the course to trigger (manual) refresh to rh.dokeos.com.
